name: 'Deploy packages'
description: 'Deploy all the packages'
runs:
  using: 'docker'
  image: 'docker://runiverse/deploy-packages'
outputs:
  deployed_packages:
    description: 'String with uploaded binaries'
